### ISSUE TITLE
Mimic can't see a function when it's called internally without the module name.

### ISSUE THREAD

**Issue by tiagodavi** [edgurgel/mimic#39] opened 2022-04-05 19:27 UTC
Hey Folks. I noticed Mimic is not able to see a function when this function is called without its module name.
For example:

```elixir
defmodule Transactions do 
  def delete(guids) do 
    delete_something(guids)
  end 

  def delete_something(guids) do 
    {:ok, guids}
  end
end

Mimic.copy(Transactions)

Transactions
|> expect(:delete_something, fn transaction_guids ->
  IO.inspect("Hey")
  {:ok, transaction_guids}
end)

Transactions.delete([])

** (Mimic.VerificationError) error while verifying mocks for #PID<0.2950.0>:
     
* expected Transactions.delete_something/1 to be invoked 1 time(s) but it has been called 0 time(s)
```

To fix this we need to call this way:

`__MODULE__.delete_something(guids)`

Can I open a PR to fix this? What do you folks think?

**Comment by jimsynz** [comment] 2022-04-05 22:26
Hi there.  This is a dupe of #27. Unfortunately it's impossible for Mimic to hook intra-module function calls because BEAM optimises this case and jumps directly to the appropriate bytecode.

**Comment by edgurgel** [comment] 2022-04-06 08:26
Thanks, @jimsynz . As @jimsynz said there's not much we can do about that. The code must call the fully qualified name `Transactions.delete_something` or it won't be possible to be stubbed. 

Maybe it's worth adding something to the README.md? :thinking:

**Closed** 2024-06-22 09:48 UTC
